### ISSUE TITLE
Add timestamps

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/uca-phantom#2]
Reading the timestamps is done the same way like the frames.
Possible implementations are:
- Reading the timestamps of a cine before the first grab and then encoding them in the frames
- Reading the timestamps at any point an make them accessible via a function or porperty

**Comment by gabs1234** [comment]
The feature was introduced in cad4a3c9719a115463e9091ebcc32df99ea30731, [`code section`](https://github.com/ufo-kit/uca-phantom/commit/cad4a3c9719a115463e9091ebcc32df99ea30731#r130960437) Hasn't been plugged in to libuca though.
